name:                data-science-utils
version:             0.1.0.1
github:              "adamConnerSax/data-science-utils"
license:             BSD3
author:              "Adam Conner-Sax"
maintainer:          "adam_conner_sax@yahoo.com"
copyright:           "2019 Adam Conner-Sax"

extra-source-files:
- Readme.md
- CHANGELOG.md

synopsis:            Various utilities for data-science work.
category:            Numerical, Visualization

description:         Please see the README on GitHub at <https://github.com/adamConnerSax/data-science-utils#readme>

dependencies:
- array >= 0.4.0.1 && <= 0.6.0.0
- base >= 4.7 && < 5
- containers >= 0.5.0.0 && <= 0.7.0.0
- declarative >= 0.5.1.0 && < 0.6.0.0
- foldl >= 1.4.5 && < 1.5
- hmatrix >= 0.18.0.0 && < 0.20.0.0
- hvega >= 0.4.0 && < 0.6
- statistics >= 0.15.0 && <0.16
- text >= 1.1.0.1 && < 1.3.0.0
- time >= 1.8.0.1 && < 1.10.0.0
- vector >= 0.12.0.1 && <= 0.13.0.0

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies

flags:
  dump-core:
    description: Dump HTML for the core generated by GHC during compilation
    default:     False
    manual:      True

library:
  ghc-options: -O -Wall
  source-dirs: src

  when:
    - condition: flag(dump-core)
      dependencies:
        - dump-core
      ghc-options:
        - -fplugin=DumpCore
        - -fplugin-opt DumpCore:core-html

